# Generated by Django 2.0.13 on 2022-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('release_date', models.IntegerField()),
                ('review_text', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('running_time', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
            ],
        ),
    ]
